title: Merry Merkle
subtitle: Giving Globally
description: "All you need is love"
author: your_name_here
timezone: UTC

language: [en]
locale: en
i18n:
  type: [page, post]
permalink_defaults:
  lang: en
i18n_dir: :lang

url: https://merrymerkle.christmas
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

highlight:
  enable: false

theme: navy
deploy:
  type: git
  repo: git@github.com:andytudhope/merrymerkle-world.git
  branch: gh-pages

twitter: cryptowanderer
github: andytudhope
